#
# Don't modify this configuration file if you don't know what are you doing.
# 
# Description: 
# 1.SaveImgSize: 保存相机出的图像
# 	  a.保存相机出的图像到本地，图像格式由3DMVS确定；
# 	  b.等于0表示不保存图像到本地，大于0表示保存图像到本地，范围为（0-2000）MB；
# 	  c.对双目和线激光相机均有效；
# 	  d.保存文件位置为: ./VolMeasureImg
# 	  d.其中imge0保存最新图像文件，imge1保存旧的图像文件

       
# 2.OutputImgEnable: API接口图像输出使能
# 	  a.0表示输出图像，1表示不输出图像；
# 	  b.仅双目直出体积，线激光349直出体积和线激光本地体积有效；
# 	  c.默认不输出，开启可能由于帧率过高导致丢数据；


# 3.DebugMode: 调试模式，0 关闭；1 开启；
#        开启后，日志记录所有操作过程，便于排查问题

# 4.算法模式: 具体值含义请参考VolumeMeasureDefine.h文件中CAMERATYPE；
#     a.范围1-13；
#     b.默认值为5，表示线激光本地积分体积算法模式；

# 5.日志文件大小: 范围[150-500]；
#     小于150，按照150生效；大于500,按照500; 105-500按照配置生效
#	


[VolMeasure]
#保存相机图像到本地大小
SaveImgSize=0

#输出图像使能
OutputImgEnable=0

#调试模式
DebugMode=0

#算法模式
AlgorithmType=5

#日志大小
LogFileSize=150


