#该配置选项配置日志大小，单位M，范围是[10,200]；配置日志文件个数，范围是[2,10]
[File]
FileSize=20
FileNum=10

#该选项配置日志等级(0-off, 1-fatal, 2-error, 3-warning, 4-info, 5-debug, 6-trace, 7-all; 级别:fatal > error > warning > info > debug > trace > all);如设置为4,则1-4级别都会打印;取消了LogDebugLevel配置选项
[Level]
LogLevel=4