
log4j.rootLogger=INFO, stdout, default
##hlog.async=false
##hlog.secret.show=true
##hlog.secret.encrypt=true


#应用于文件回滚
log4j.logger.default=ALL, default
log4j.appender.default=org.apache.log4j.RollingFileAppender
log4j.appender.default.File=./Log/Fusion.log
log4j.appender.default.MaxFileSize=100MB
log4j.appender.default.MaxBackupIndex=2
log4j.appender.default.Append=true
log4j.appender.default.Threshold=ALL
log4j.appender.default.layout=org.apache.log4j.PatternLayout
log4j.appender.default.layout.ConversionPattern=%d [%t] %-5p %.16c - %m%n
log4j.additivity.default = false