[BinoVol]
#补偿系数，在测量结果后加减对应的值
#支持设置范围[-999,999],整数值
#如超出此范围，则修改为0
CompensateLength=0
CompensateWidth=0
CompensateHeight=0


#稳定时允许的最大波动值
#支持设置范围[0,999],整数值
#如超出此范围，则修改为20
MaxDisparityLength=20
MaxDisparityWidth=20
MaxDisparityHeight=20

#需要连续稳定的次数
#支持设置范围[1,15],整数值
#如超过此范围，则修改为3
StableCalCount=3

#配置为1后，可以渲染深度图
#仅双目PC计算体积有效
DisplayDepth=0

#轮廓定位使能 开启:1,关闭:0,此功能当前版本无效；
ContourTracingEnable=0

#常规体积 0 ，积分体积 1
VolumeAlgorithmLibraryType=1


#多增益数量
#支持设置范围[1,2],整数值
#如超过此范围，则修改为2
#当设置为2时，按2组增益值和曝光值生效；如设置为非2时，仅第一组增益和曝光值生效
SwitchParamNum=2

#多增益值
#支持设置范围[1000,15000],整数值
#如超过此范围，则修改为8000
Gain0=1000
Gain1=10000

#多曝光值
#支持设置范围[100,2000],整数值
#如超过此范围，则修改为1049
Exp0=1049
Exp1=1049
