#
# Don't modify this configuration file if you don't know what are you doing.
# 
# Description: 
# 1.LogEnable: 日志输出使能 
#	True-创建日志 False-不创建日志(默认创建日志)
# 2.Models: 设备类型
# 3.NodeCount: 缓存节点数量(范围:1~12个)
#   NodeSize: 单个缓存节点大小(单位:KB, 范围:1024KB~20480KB)
# 4.WaybillRotateEnable：面单自动旋正使能
#   True-面单旋正 False-面单直接输出(默认直接输出)
[LogConfig]
LogEnable=True

[CameraSeries]
Models=MV-SI,MV-IH,MV-IM,MV-IL,MV-ID,MV-PD010003-21IH,MV-PD010003-23IH,

[CacheNode]
NodeCount=3
NodeSize=2048

[Waybill]
WaybillRotateEnable=False

